steps:
# Deploy to Cloud Run, no traffic
- id: Deploy latest to Cloud Run
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['run','deploy', 'cd-cloudbuild-app', '--image', 'gcr.io/agmsb-k8s/cd-cloudbuild-app:latest', '--region', 'us-central1', '--platform', 'managed', '--no-traffic']
# Deploy to Cloud Run, update traffic
- id: Update 20% traffic to latest
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - -c
    - |
      gcloud run services update-traffic cd-cloudbuild-app --to-revisions LATEST=20 --region us-central1
# Issue traffic to Cloud Run app
- id: Generate traffic
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: 
    - -c
    - |
      gcloud auth print-identity-token
      for i in {1..200}
      do
        curl -H "Authorization: Bearer $(gcloud auth print-identity-token)" https://cd-cloudbuild-app-tjjxnhbjna-uc.a.run.app
      done
options:
  logging: CLOUD_LOGGING_ONLY
